"""Add shop_ids to price.

Revision ID: 98832770736b
Revises: 11b434c7dc5a
Create Date: 2024-05-24 16:48:56.000439

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "98832770736b"
down_revision = "11b434c7dc5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("shop_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "shop_ids")
    # ### end Alembic commands ###
