"""Add extra price field.

Revision ID: 76174876617a
Revises: aa8f21d1e3c2
Create Date: 2024-07-12 12:21:22.794686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76174876617a"
down_revision = "aa8f21d1e3c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("cannabis", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "cannabis")
    # ### end Alembic commands ###
