"""shop group id products kinds.

Revision ID: aa8f21d1e3c2
Revises: 0b238d35dcee
Create Date: 2024-06-30 17:33:09.219921

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa8f21d1e3c2"
down_revision = "0b238d35dcee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kinds", sa.Column("shop_group_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "kinds", "shop_groups", ["shop_group_id"], ["id"])
    op.add_column("products", sa.Column("shop_group_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "products", "shop_groups", ["shop_group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "shop_group_id")
    op.drop_constraint(None, "kinds", type_="foreignkey")
    op.drop_column("kinds", "shop_group_id")
    # ### end Alembic commands ###
