"""shop group id table.

Revision ID: 5cf8f01eda8b
Revises: 11b434c7dc5a
Create Date: 2024-06-01 14:51:55.782494

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5cf8f01eda8b"
down_revision = "11b434c7dc5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_groups",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("shop_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_groups_id"), "shop_groups", ["id"], unique=False)
    op.create_index(op.f("ix_shop_groups_name"), "shop_groups", ["name"], unique=True)
    op.add_column("prices", sa.Column("shop_group_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint("prices_internal_product_id_key", "prices", type_="unique")
    op.create_unique_constraint("_internal_product_shop_group_uc", "prices", ["internal_product_id", "shop_group_id"])
    op.create_foreign_key(None, "prices", "shop_groups", ["shop_group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.drop_constraint("_internal_product_shop_group_uc", "prices", type_="unique")
    op.create_unique_constraint("prices_internal_product_id_key", "prices", ["internal_product_id"])
    op.drop_column("prices", "shop_group_id")
    op.drop_index(op.f("ix_shop_groups_name"), table_name="shop_groups")
    op.drop_index(op.f("ix_shop_groups_id"), table_name="shop_groups")
    op.drop_table("shop_groups")
    # ### end Alembic commands ###
